### PR TITLE
Add Ogre 2.2 (For Ignition Fortress)

### PR DESCRIPTION
**Pull request by chapulina**
* Follow up to #128 , it's currently not possible to install `ignition-fortress` just with packages.ros.org

I copied what we have for Ogre 2.1 on Citadel:

https://github.com/ros-infrastructure/reprepro-updater/blob/78a5edd2dad41479dcc3ead254eb6db2dc7bbd9f/config/ignition_citadel_gazebo11_ubuntu_focal.yaml#L126-L129

These are the versions we have on packages.osrfoundation.org

```
libogre-2.2-dev/unknown,now 2.2.5+20210824~ec3f70c-4osrf~focal amd64 [installed]
libogre-2.2/unknown,now 2.2.5+20210824~ec3f70c-4osrf~focal amd64 [installed,automatic]
ogre-2.2-doc/unknown,unknown 2.2.5+20210824~ec3f70c-4osrf~focal all
ogre-2.2-tools/unknown 2.2.5+20210824~ec3f70c-4osrf~focal amd64
```

### CODE REVIEW

**Comment by cottsay** [comment]
CI failure should be resolved by #137

**Comment by j-rivero** [comment]
Imported in build.ros.org [Build Status](https://build.ros.org/job/import_upstream/203/)

**Comment by chapulina** [comment]
Thanks! I don't see it here yet, is it a matter of time, or extra steps?

**Comment by chapulina** [comment]
It's there now! Thanks!

http://packages.ros.org/ros2/ubuntu/pool/main/o/ogre-2.2/

**Comment by j-rivero** [comment]
Imported into build.ros2.org [Build Status](https://build.ros2.org/job/import_upstream/364/)

**Pull request merged**
