### PR TITLE
Update 6 recently released colcon packages

### PR DESCRIPTION
**Pull request by cottsay**
Packages pushed to: https://packagecloud.io/dirk-thomas/colcon

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Could we get f19b710 into its own PR so that it doesn't get squashed out of the history?

**Comment by cottsay** [comment]
> Could we get [f19b710](https://github.com/ros-infrastructure/reprepro-updater/commit/f19b71051971d99efdd57fa1c0846d50e1758ca6) into its own PR so that it doesn't get squashed out of the history?

Done: #137

**Comment by cottsay** [comment]
...and rebased, now that #137 is merged.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by cottsay** [comment]
Import is done:
* https://build.ros2.org/job/import_upstream/363/
* https://build.ros.org/job/import_upstream/204/

**Pull request merged**
