### PR TITLE
add wily to suites to import for collada-dom

### PR DESCRIPTION
**Pull request by wjwwood**
See: https://github.com/ros/rosdistro/issues/9945#issuecomment-194642340

### CODE REVIEW

**Comment by wjwwood** [comment]
We may have to include Xenial in this list but with a partial import rule (not sure that's possible), see: https://github.com/ros/rosdistro/pull/10673

**Comment by tfoote** [comment]
lgtm

**Comment by k-okada** [comment]
@wjwwood I'm not sure how this works, but can we put arm deb to ros repository if we add `armhf`?

**Comment by tfoote** [comment]
We can also import armhf and arm64 debs if you build them.

**Pull request merged**
