### PR TITLE
Update catkin_lint upstream to new PPA

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Per discussion in https://github.com/ros/rosdistro/issues/24251

### CODE REVIEW

**Review by roehling — COMMENTED** [review]
Trusty is EOL since April 2019 and no longer part of the PPA.

If you want to lock to a specific version, I suggest 1.6.10-* as wildcard (include the dash), otherwise .1* might also match .10 to .19

**Comment by nuclearsandwich** [comment]
I've removed trusty from the import configuration.

**Review by roehling — APPROVED** [review]
LGTM

**Comment by nuclearsandwich** [comment]
> If you want to lock to a specific version, I suggest 1.6.10-* as wildcard (include the dash), otherwise .1* might also match .10 to .19

As written it was `.10*` which using the glob format would match `100` - `109`. as well as .10. So adding the dash is still an improvement.

**Comment by gavanderhoorn** [comment]
Thanks @nuclearsandwich :+1: 

And @roehling :+1:

**Comment by nuclearsandwich** [comment]
Import jobs: 
* http://build.ros.org/job/import_upstream/137/
* http://build.ros2.org/job/import_upstream/293/

**Pull request merged**
