### PR TITLE
New catkin-lint release 1.6.22

### PR DESCRIPTION
**Pull request by roehling**

### CODE REVIEW

**Comment by peci1** [comment]
@roehling Will you please update this to 1.6.22?

**Comment by roehling** [comment]
Bumped

**Comment by peci1** [comment]
@cottsay @nuclearsandwich Guys, this has been hanging around for 6 months now... Could you please merge it?

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/new-packages-for-iron-irwini-2023-06-30/32169/6

**Review by cottsay — APPROVED** [review]
This one clearly slipped through the cracks. I apologize.

**Comment by peci1** [comment]
Great! This release would be a first step towards running catkin_lint on the buildfarm. There are still two pieces missing: https://github.com/ros-infrastructure/rosdep/pull/908 and https://github.com/ros-infrastructure/ros_buildfarm/pull/987 . Is there a chance they would get on the radar again? :)

**Comment by cottsay** [comment]
[Build Status](https://build.ros2.org/job/import_upstream/454/)
[Build Status](https://build.ros.org/job/import_upstream/279/)

**Pull request merged**
