### PR TITLE
Update fortress jammy: ign-cmake, rendering and gazebo6

### PR DESCRIPTION
**Pull request by j-rivero**
Probably fixes https://github.com/gazebosim/gz-cmake/issues/304

### CODE REVIEW

**Comment by chapulina** [comment]
Should we also update Focal? We actually have it duplicate in 2 places, we should remove one of them so we don't need to keep them in sync:

https://github.com/ros-infrastructure/reprepro-updater/blob/34039da99c40192097048bb24247a8240468518c/config/ignition_fortress_ubuntu_focal.yaml#L9-L11

https://github.com/ros-infrastructure/reprepro-updater/blob/34039da99c40192097048bb24247a8240468518c/config/ignition_citadel_gazebo11_ubuntu_focal.yaml#L17-L19

**Review by chapulina — APPROVED** [review]
Approving to unblock the fix. We should only need to upgrade Jammy for the fix, since the issue was introduced only on Jammy here:

* https://github.com/ros-infrastructure/reprepro-updater/pull/160

**Comment by j-rivero** [comment]
> Approving to unblock the fix. We should only need to upgrade Jammy for the fix, since the issue was introduced only on Jammy here:

Yep, let's fix jammy by now. We'll update focal later. I've added a couple more of imports.

**Comment by vatanaksoytezer** [comment]
@j-rivero @chapulina thank you for addressing this super quickly!

**Comment by j-rivero** [comment]
I'm pretty sure that this will fix problems at least up to RVIZ deps. Merging and syncing.

**Pull request merged**
