### PR TITLE
Update Fortress packages in Ubuntu Focal

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Generated from #144.

### CODE REVIEW

**Review by chapulina — APPROVED** [review]
All versions LGTM, thanks!

**Comment by chapulina** [comment]
Oh wait, just saw this is Focal. Should we remove them after we have Jammy?

**Comment by nuclearsandwich** [comment]
> Oh wait, just saw this is Focal. Should we remove them after we have Jammy?

Because Fortress is for Rolling/Humble?
Since we've ended up with Focal as a tier 3 platform for Humble, I think we can continue importing Fortress on Focal as long as it's supported by the Gazebo team.

**Comment by chapulina** [comment]
> Since we've ended up with Focal as a tier 3 platform for Humble

Oh I missed that. Yeah makes sense then 👍🏽

**Comment by nuclearsandwich** [comment]
Import jobs:
* https://build.ros.org/job/import_upstream/227/
* https://build.ros2.org/job/import_upstream/388/

**Pull request merged**
