### PR TITLE
bump colcon-ed to 0.1.2

### PR DESCRIPTION
**Pull request by Briancbn**
Signed-off-by: Chen Bainian <chenbn@artc.a-star.edu.sg>

Releasing updated version based on @dirk-thomas's new release instruction.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
It doesn't look like the Debian package has been released yet: https://packagecloud.io/app/dirk-thomas/colcon/search?q=colcon-ed

I think you haven't created a packagecloud.io account or haven't requested to be added as a contributor to that repository yet (see https://colcon.readthedocs.io/en/released/developer/release.html#first-time-setup):

> Configure credentials for packagecloud.io and request to be added as a contributor to the colcon repository

**Comment by Briancbn** [comment]
> haven't requested to be added as a contributor to that repository

I can't seem to be able to submit a request of sort. Maybe you can add me directly? https://packagecloud.io/Briancbn

**Comment by dirk-thomas** [comment]
> maybe you can add me directly? https://packagecloud.io/Briancbn

**Comment by dirk-thomas** [comment]
> maybe you can add me directly? https://packagecloud.io/Briancbn

Done.

**Comment by Briancbn** [comment]
Thanks, debs are uploaded. https://packagecloud.io/app/dirk-thomas/colcon/search?q=colcon-ed

**Review by dirk-thomas — APPROVED** [review]

**Comment by dirk-thomas** [comment]
@nuclearsandwich Please merge and import after reviewing. Thanks.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
Import jobs
* http://build.ros.org/job/import_upstream/140/
* http://build.ros2.org/job/import_upstream/296/

**Pull request merged**
